packages:
  - "packages/*"
  - "apps/*"
  - "plugins/**/*"
  - "!**/__tests__/**"
allowBuilds:
  '@google/genai': set this to true or false
  bufferutil: set this to true or false
  esbuild: true
  msw: set this to true or false
  protobufjs: set this to true or false
